.

diff --git a/src/thepkg.patch b/src/thepkg.patch
--- a/src/thepkg.patch
+++ b/src/thepkg.patch
@@ -79,6 +79,11 @@
 +			"  (requires: thepkg-noerr-stat0)" \
 +			"  [thepkg-extended-verbose]" \
 +			"    (1 for now!) print longer messages" \
++			"" \
++			"  (writing ! -> testing )" \
++			"  [thepkg-rmfailed]" \
++			"     when removing files failed," \
++			"     then keep manifest.rmfailed" \
  		; # [patches] help message patches -> patches applyed
  		exit
  	;;
@@ -97,7 +102,7 @@
  
  # thepkg file detection:
 -# [patch: thepkg-addfromtar] thepkg file detection
-+thepkgname=${1##*/}
+-thepkgname=${1##*/}
 +unset tar_file
  case $1 in
  	'') err "please specify thepkgname or see --help";;
@@ -175,6 +180,16 @@
  	[ -e "$THEPKG_DBPATH/$thepkgname" ] || {
  		err "The pkg '$thepkgname' is not installed" 2
  	}
+ 	manifest_path=$THEPKG_DBPATH/$thepkgname/manifest
+ 	# thepkg pre del
+-	# [patch: thepkg-rmfailed] pre del
++	unset _patch_thepkg_rmfailed__exit_on_fail
++	if [ -e "$manifest_path.rmfailed" ];
++		manifest_path=$manifest_path.rmfailed
++		_patch_thepkg_rmfailed__exit_on_fail=''
++		###err "The pkg '$thepkgname' haven not been removed last time" 2 # todo: is this good error message
++	fi
+ 	
  	log "Removing the pkg '$thepkgname'..."
  	(
  		cd "${THEPKG_PREFIX:-/}" || exit
@@ -186,18 +201,26 @@
  					rmdir -v "$file" 2>/dev/null || :
  				;;
  				*)
- 					rm -v "$file"
+ 					rm -v "$file" || {
+ 						# thepkg del rm failed
+-						# [patch: thepkg-rmfailed] thepkg del rm failed
++						case ${_patch_thepkg_rmfailed__exit_on_fail+x} in
++							x) false;;
++							*) printf %s\\n "$file" >> "$THEPKG_DBPATH/$thepkgname"/manifest.rmfailed;;
++						esac || \
+ 						false
+ 					}
  				;;
  			esac
  		done
- 	) < "$THEPKG_DBPATH/$thepkgname"/manifest
+ 	) < "$manifest_path"
  	
- 	rm -v "$THEPKG_DBPATH/$thepkgname"/manifest
+ 	rm -v "$manifest_path"
  	# thepkg post manifest removal:
 -	# [patch: thepkg-metadata-thepkg-ext] thepkg post manifest removal
 +	# TODO: # [patch: thepkg-metadata-thepkg-ext] thepkg post manifest removal
  
  	rmdir -v "$THEPKG_DBPATH/$thepkgname"
  	;;
- *) err "use --help";;
+ *) err "see --help";;
  esac
diff --git a/thepkg b/thepkg
--- a/thepkg
+++ b/thepkg
@@ -43,6 +43,7 @@ shift
 
 # thepkg file detection:
 # [patch: thepkg-addfromtar] thepkg file detection
+thepkgname=${1##*/}
 case $1 in
 	'') err "please specify thepkgname or see --help";;
 # [patch: thepkg-addfromtar] thepkg file detection -> case
@@ -92,6 +93,10 @@ del)
 	[ -e "$THEPKG_DBPATH/$thepkgname" ] || {
 		err "The pkg '$thepkgname' is not installed" 2
 	}
+	manifest_path=$THEPKG_DBPATH/$thepkgname/manifest
+	# thepkg pre del
+	# [patch: thepkg-rmfailed] pre del
+	
 	log "Removing the pkg '$thepkgname'..."
 	(
 		cd "${THEPKG_PREFIX:-/}" || exit
@@ -102,13 +107,17 @@ del)
 					rmdir -v "$file" 2>/dev/null || :
 				;;
 				*)
-					rm -v "$file"
+					rm -v "$file" || {
+						# thepkg del rm failed
+						# [patch: thepkg-rmfailed] thepkg del rm failed
+						false
+					}
 				;;
 			esac
 		done
-	) < "$THEPKG_DBPATH/$thepkgname"/manifest
+	) < "$manifest_path"
 	
-	rm -v "$THEPKG_DBPATH/$thepkgname"/manifest
+	rm -v "$manifest_path"
 	# thepkg post manifest removal:
 	# [patch: thepkg-metadata-thepkg-ext] thepkg post manifest removal
 
diff --git a/thepkg-allpatched b/thepkg-allpatched
--- a/thepkg-allpatched
+++ b/thepkg-allpatched
@@ -73,6 +73,11 @@ case $1 in
 			"  (requires: thepkg-noerr-stat0)" \
 			"  [thepkg-extended-verbose]" \
 			"    (1 for now!) print longer messages" \
+			"" \
+			"  (writing ! -> testing )" \
+			"  [thepkg-rmfailed]" \
+			"     when removing files failed," \
+			"     then keep manifest.rmfailed" \
 		; # [patches] help message patches -> patches applyed
 		exit
 	;;
@@ -90,7 +95,6 @@ esac
 shift
 
 # thepkg file detection:
-thepkgname=${1##*/}
 unset tar_file
 case $1 in
 	'') err "please specify thepkgname or see --help";;
@@ -160,6 +164,13 @@ del)
 	[ -e "$THEPKG_DBPATH/$thepkgname" ] || {
 		err "The pkg '$thepkgname' is not installed" 2
 	}
+	manifest_path=$THEPKG_DBPATH/$thepkgname/manifest
+	# thepkg pre del
+	if [ -e "$manifest_path.rmfailed" ];
+		manifest_path=$manifest_path.rmfailed
+		###err "The pkg '$thepkgname' haven not been removed last time" 2 # todo: is this good error message
+	fi
+	
 	log "Removing the pkg '$thepkgname'..."
 	(
 		cd "${THEPKG_PREFIX:-/}" || exit
@@ -170,13 +181,17 @@ del)
 					rmdir -v "$file" 2>/dev/null || :
 				;;
 				*)
-					rm -v "$file"
+					rm -v "$file" || {
+						# thepkg del rm failed
+						printf %s\\n "$file" >> "$THEPKG_DBPATH/$thepkgname"/manifest.rmfailed || \
+						false
+					}
 				;;
 			esac
 		done
-	) < "$THEPKG_DBPATH/$thepkgname"/manifest
+	) < "$manifest_path"
 	
-	rm -v "$THEPKG_DBPATH/$thepkgname"/manifest
+	rm -v "$manifest_path"
 	# thepkg post manifest removal:
 	# TODO: # [patch: thepkg-metadata-thepkg-ext] thepkg post manifest removal
 
